import { Metadata } from "next";

export const metadata: Metadata = {
    // title: "My Blog" || "Default Title", // Fallback if `null` or `undefined`
    description: "Generated by create next app",
  };
  
  

export default function Head() {
  return (
    <>
      <meta name="description" content={metadata.description || ""} />
      {/* <title>{metadata.title}</title> */}
    </>
  );
}
